menu.nombre.principal=Principal
menuitem.nombre.salir=Salir
menu.nombre.personas=Personas
menuitem.nombre.paciente=Pacientes
menuitem.nombre.medico=Médicos
menuitem.nombre.enfermero=Enfermeros
menu.nombre.catalogos=Catálogos
menuitem.nombre.especialidad=Especialidades
menuitem.nombre.horario=Horarios
menu.nombre.seguridad=Seguridad
menuitem.nombre.usuario=Usuarios
menu.nombre.atencion=Atención
menuitem.nombre.cita=Registrar Cita
menuitem.nombre.checkin=Check-in
menuitem.nombre.triaje=Triaje
menuitem.nombre.consulta=Consulta
menuitem.nombre.ticket=Imprimir Ticket
menu.nombre.reporte=Reportes
menuitem.nombre.reporte=Citas
menu.nombre.estilo=Cambiar Estilo
menu.nombre.idioma=Idioma
boton.guardar=Guardar
boton.cancelar=Cancelar
boton.editar=Editar
boton.eliminar=Eliminar
boton.nuevo=Nuevo
boton.limpiar=Limpiar
boton.modificar=Modificar
toast.error.credenciales=Credenciales inválidas. Intente nuevamente
toast.exito.cita=Cita registrada. Ticket: %s
